image: barichello/godot-ci:4.2.2

# NOTE: the `cd` command in each build stage is not necessary if your
# project.godot is at the repo root

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .godot/imported/

stages:
  - import-assets
  - export
  - deploy

variables:
  EXPORT_NAME: Twin-Stick

# Open the editor to import assets in case the cache was empty or outdated
import-assets:
  stage: import-assets
  script:
    # - godot -v -e --headless --quit-after 1000
    - godot -v --headless --import

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    # - cd $EXPORT_NAME
    - godot -v --export-release --headless "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    # - cd $EXPORT_NAME
    - godot -v --export-release --headless "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

# Itch.io Deploy
itchio:linux:
  stage: deploy
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux --userversion-file buildnumber.txt
  dependencies:
    - linux

itchio:windows:
  stage: deploy
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows --userversion-file buildnumber.txt
  dependencies:
    - windows
